### ISSUE TITLE
Storytel-API in JS

### ISSUE THREAD

**Issue by MauritsWilke** [javsanpar/storytel-tui#11]
Hi there! I was wondering if it's okay with you to take some parts of your code (mainly password_crypt.rs) to make a storytel-api wrapper in JS. Of course you will get credit for this.

**Comment by javsanpar** [comment]
Hi! Of course, you can take all you want! I think that as you are not going to do a direct derivate work you can put it the license you want, but I encourage you to choose a GPL license.

**Comment by MauritsWilke** [comment]
Thanks a lot! I have it under MIT right now, what does GPL offer over MIT?

**Comment by javsanpar** [comment]
The main difference is that GPL forbids distributing closed source versions of your project and MIT let anyone do this.

You can check this links if you want to learn more about the differences:
- https://choosealicense.com/licenses/gpl-3.0/
- https://choosealicense.com/licenses/mit/
- https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#summary
- https://tldrlegal.com/license/mit-license#summary

**Comment by MauritsWilke** [comment]
Ah right well enforcing open source sounds nice, guess ill switch :)
