### ISSUE TITLE
How did you obtain AES `key` & `iv`?

### ISSUE THREAD

**Issue by nipunsadvilkar** [javsanpar/storytel-tui#15]
Question out of curiosity, how did you obtain these `key` and `iv` values?
https://github.com/javsanpar/storytel-tui/blob/022ca1bb0193eee727793f981b1f1c0dbefba1f1/src/password_crypt.rs#L3-L4

**Comment by javsanpar** [comment]
Hi! APK decompilation

**Comment by nipunsadvilkar** [comment]
Got it thanks!
