### ISSUE TITLE
error[E0432]: unresolved import `syn::export`

### ISSUE THREAD

**Issue by s3prakash** [javsanpar/storytel-tui#3]
Hi,

I see the below error when compiling the code using Cargo.

==========
Compiling enumset_derive v0.4.4
error[E0432]: unresolved import `syn::export`
  --> /home/sivas/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.4.4/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `enumset_derive`

=======
https://github.com/nushell/nushell/issues/2867 

The above link shows the crux of the issue. Seems to be an issue with the crate syn. A older version of syn will fix this is whtais being said.

Please let me know if this issue could be fixed.

Thanks,
I'm an user of Storytel

**Comment by javsanpar** [comment]
Hi!

I can not reproduce your problem, I do not have errors when compiling.

Which OS and version of rust are you using?

Thank you for trying storytel-tui!

**Comment by s3prakash** [comment]
sivas@pop-os:/etc/apt$ uname -a
Linux pop-os 5.11.0-7620-generic #21~1624379747~21.04~3abeff8-Ubuntu SMP Wed Jun 23 02:34:03 UTC  x86_64 x86_64 x86_64 GNU/Linux

I'm having brand new installation of Pop OS 21.04

sivas@pop-os:~/programs/git/storytel-tui$ rustc --version
rustc 1.50.0

**Comment by s3prakash** [comment]
Hi, 

I have no experience with Rust. But let me know if any additional debug messages are needed. Thanks for helping with this. 

Thank you.

**Comment by javsanpar** [comment]
I just pushed a fix, 624bd42. Try it if you can.

The repository did not have a Cargo.lock file, so you built the project with dependencies and versions different from the ones I used.

Still, I have to check why the project do not compile with the latest versions of the dependencies.

**Comment by s3prakash** [comment]
Hi, 

Now the compiling is successful but the linking process fails as below.

x-gnu/lib/libcompiler_builtins-eb6c1ebbc79c2607.rlib" "-Wl,-Bdynamic" "-lmpv" "-lssl" "-lcrypto" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lmpv
          collect2: error: ld returned 1 exit status


Caused by:
  process didn't exit successfully: `rustc --crate-name storytel_tui --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C metadata=64d8cf0b0cf94f22 -C extra-filename=-64d8cf0b0cf94f22 --out-dir /home/sivas/programs/git/storytel/storytel-tui/target/release/deps -L dependency=/home/sivas/programs/git/storytel/storytel-tui/target/release/deps --extern cursive=/home/sivas/programs/git/storytel/storytel-tui/target/release/deps/libcursive-7ff0cc4937ce0fe4.rlib --extern mpv=/home/sivas/programs/git/storytel/storytel-tui/target/release/deps/libmpv-83e634866953da46.rlib --extern openssl=/home/sivas/programs/git/storytel/storytel-tui/target/release/deps/libopenssl-32c458b35eef09a4.rlib --extern reqwest=/home/sivas/programs/git/storytel/storytel-tui/target/release/deps/libreqwest-f6e875f3d6896b9e.rlib --extern serde=/home/sivas/programs/git/storytel/storytel-tui/target/release/deps/libserde-c01f1dd8554ff6c1.rlib --extern serde_json=/home/sivas/programs/git/storytel/storytel-tui/target/release/deps/libserde_json-39a35d0b2004e7b0.rlib
  ` (exit code: 1)

mpv player is installed and I can see libmpv.so.1 file under /usr/lib/x86_64-linux-gnu/ folder. Not sure if libmpv.so and libmpv.so.1 are same. Please let know if you can shed some light.

Thanks much.

**Comment by s3prakash** [comment]
sivas@pop-os:/usr$ find . -name libmpv.so -print
sivas@pop-os:/usr$ find . -name libmpv.so.1 -print
./lib/x86_64-linux-gnu/libmpv.so.1
sivas@pop-os:/usr$ sudo apt install mpv
[sudo] password for sivas: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mpv is already the newest version (0.32.0-2ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sivas@pop-os:/usr$

**Comment by javsanpar** [comment]
It seems that in Debian/Ubuntu/POP-OS you need a specific package to get the dev files. Install `libmpv-dev`and try again.

Let me know if it works for you!

**Comment by s3prakash** [comment]
Yes.It worked. Thanks a lot. I'm enjoying Storytel on my desktop now. I'm closing this issue now.
