### ISSUE TITLE
Not workign - closes after entering credentials.

### ISSUE THREAD

**Issue by myszkin81** [javsanpar/storytel-tui#5]

**Comment by javsanpar** [comment]
Hello!

Are you using Storytel from India? I suspect that Storytel India has different API than Spain.

**Comment by myszkin81** [comment]
Storytel Poland. Maybe a different API. It would be nice to get an error message tho :)

**Comment by javsanpar** [comment]
> Storytel Poland. Maybe a different API.

Could you make a capture with mitmproxy of the traffic generated by the Storytel application you have installed on your phone? This way, I can try to add support for your country.

> It would be nice to get an error message tho :)

Yes, you are right. The app is basic and unpolished. Most errors are unhandled and end on crash

**Comment by falkenhawk** [comment]
Does storytel have a documentation of its api published somewhere? Or is it all about reverse-engineering it?

**Comment by javsanpar** [comment]
There is no documentation. As you said, is all about reverse-engineering it.

**Comment by myszkin81** [comment]
> Could you make a capture with mitmproxy of the traffic generated by the Storytel application you have installed on your phone? This way, I can try to add support for your country.

I am using iPhone, so I can't do it. Sorry.

**Comment by javsanpar** [comment]
It can be done in IOS/IPhone. In fact, it is easier than in Android.

I did a fast search and found this tutorial: https://www.garyjackson.dev/posts/intercepting-ios-communication/

**Comment by javsanpar** [comment]
I applied a patch to the project and I think it should fix the problem you had. If you want you can try it again!
