### ISSUE TITLE
Can't compile package

### ISSUE THREAD

**Issue by Elagoht** [javsanpar/storytel-tui#8]
It fails and says that:

```
error[E0432]: unresolved import `syn::export`
  --> /home/furkan/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.4.4/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `enumset_derive` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `storytel-tui v0.1.0 (/home/furkan/Desktop/storytel-tui-master)`, intermediate artifacts can be found at `/home/furkan/Desktop/storytel-tui-master/target`
```

**Comment by javsanpar** [comment]
Hi! Thank you for your interest in storytel-tui.

Can you run `cargo clean; cargo build -vv 2>&1 | tee /tmp/cargo.log` and attach the generated file here?

**Comment by Elagoht** [comment]
[cargo.log](https://github.com/javsanpar/storytel-tui/files/9115623/cargo.log)
I dont know why but after running this command I was able to install. It runs now. Thanks.

**Comment by javsanpar** [comment]
Commit 6d71aec40 should have fixed your problem. Maybe you pulled this commit.

Anyway, thank you for your interest in storytel-tui!
